version: "3"
services:
  frontend:
    build:
      context: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  backend:
    build:
      context: "./backend"
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - "./backend:/app"

networks:
  mynetwork:
