version: "3"
services:
  frontend:
    build:
      context: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - mynetwork
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  backend:
    build:
      context: "./backend"
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - "./backend:/app"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - mynetwork

networks:
  mynetwork:
